#/bin/bash
#   fedora_install.sh  Copyright (C) 2020 Arvind Mukund <armu30@gmail.com> 
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Installs all the essential packages.
echo "[*] Installing packages" 
sudo dnf update
sudo dnf upgrade
sudo dnf group install "Development Tools"
sudo dnf install neovim  openssl-devel git git-email gimp \
cmake clang clang-tools-extra ruby gdb python3-devel python3-pip\
qemu  geany hexedit nmap nasm curl patchelf radare2 radare2-devel

# Installs libc one_gadget identifier.
echo "[*] Installing one_gadget"
sudo gem install one_gadget

# Installs custom gnome based accels shortcut
echo "[*] Installing terminal shortcuts"
./write_terminal_shortcut.sh

# Installs a few python packages
pip3 install --user -r ./requirements.txt
DATE=$(date)
echo -ne "\n# Generated by fedora_install.sh at $DATE\n" >> $HOME/.bashrc
echo -ne "export PATH=\"\$HOME/.local/bin:\$PATH\"\n\n" >> $HOME/.bashrc

## AYYYY
echo "[.] ALL DONE! Enjoy this now decent linux distribution"

