#/bin/bash
#   ubuntu_install.sh  Copyright (C) 2020 Arvind Mukund <armu30@gmail.com> 
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Installs all the essential packages.
echo "[*] Installing packages" 
sudo apt-get install -y neovim build-essential libcurl4-gnutls-dev \
libxml2-dev libssl-dev git git-email gimp cmake clang clang-tools \
clang-format clang-tidy ruby gdb python3-dev python3-pip libglib2.0-dev \
libc6-dbg qemu qemu-system geany python-is-python3 gcc-multilib hexedit nmap nasm curl patchelf

# Installs libc one_gadget identifier.
echo "[*] Installing one_gadget"
sudo gem install one_gadget

# Installs custom gnome based accels shortcut
echo "[*] Installing terminal shortcuts"
./write_terminal_shortcut.sh

# Downloads and installs radare2 continous
./download_radare.sh

# Installs a few python packages
pip3 install --user -r ./requirements.txt
DATE=$(date)
echo -ne "\n# Generated by ubuntu_install.sh at $DATE\n" >> $HOME/.bashrc
echo -ne "export PATH=\"\$HOME/.local/bin:\$PATH\"\n\n" >> $HOME/.bashrc

## AYYYY
echo "[.] ALL DONE! Enjoy this now decent linux distribution"

